import type { BattleAssetEntry } from '../types/battleTypes';

/** 唯一 runtime media manifest；概念板與遠端素材不進此表。 */
export const BATTLE_ASSET_REGISTRY: Readonly<{ assets: readonly BattleAssetEntry[] }> = {
  assets: [
    // 角色 Base (Idle) Entries
    {
      id: 'hero',
      src: '/battle/hero.webp',
      kind: 'character',
      action: 'idle',
      fallbackId: null,
      width: 500,
      height: 500,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'right',
      visualScale: 1,
      opaque: false,
    },
    {
      id: 'slime_blue',
      src: '/battle/monsters/slime_blue.webp',
      kind: 'character',
      action: 'idle',
      fallbackId: 'hero',
      width: 500,
      height: 500,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1,
      opaque: false,
    },
    {
      id: 'goblin_green',
      src: '/battle/monsters/goblin_green.webp',
      kind: 'character',
      action: 'idle',
      fallbackId: 'hero',
      width: 500,
      height: 500,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1,
      opaque: false,
    },
    {
      id: 'bat_shadow',
      src: '/battle/monsters/bat_shadow.webp',
      kind: 'character',
      action: 'idle',
      fallbackId: 'hero',
      width: 500,
      height: 500,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1,
      opaque: false,
    },
    {
      id: 'skeleton_warrior',
      src: '/battle/monsters/skeleton_warrior.webp',
      kind: 'character',
      action: 'idle',
      fallbackId: 'hero',
      width: 500,
      height: 500,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1.25,
      opaque: false,
    },
    {
      id: 'orc_berserker',
      src: '/battle/monsters/orc_berserker.webp',
      kind: 'character',
      action: 'idle',
      fallbackId: 'hero',
      width: 500,
      height: 500,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1.25,
      opaque: false,
    },
    {
      id: 'dragon_fire',
      src: '/battle/monsters/dragon_fire.webp',
      kind: 'character',
      action: 'idle',
      fallbackId: 'hero',
      width: 500,
      height: 500,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1.5,
      opaque: false,
    },
    {
      id: 'skeleton_wizard',
      src: '/battle/monsters/skeleton_wizard.webp',
      kind: 'character',
      action: 'idle',
      fallbackId: 'hero',
      width: 677,
      height: 369,
      anchor: { x: 0.5, y: 0.9 },
      facing: 'left',
      visualScale: 1.8,
      opaque: false,
    },

    // 26 個 Character Action Entries
    // Hero Actions (4)
    {
      id: 'hero:attack',
      src: '/battle/hero_attack.webp',
      kind: 'character',
      action: 'attack',
      fallbackId: 'hero',
      width: 320,
      height: 819,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'right',
      visualScale: 1,
      opaque: false,
    },
    {
      id: 'hero:cast',
      src: '/battle/hero_cast.webp',
      kind: 'character',
      action: 'cast',
      fallbackId: 'hero',
      width: 320,
      height: 819,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'right',
      visualScale: 1,
      opaque: false,
    },
    {
      id: 'hero:hurt',
      src: '/battle/hero_hurt.webp',
      kind: 'character',
      action: 'hurt',
      fallbackId: 'hero',
      width: 320,
      height: 819,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'right',
      visualScale: 1,
      opaque: false,
    },
    {
      id: 'hero:defeat',
      src: '/battle/hero_defeat.webp',
      kind: 'character',
      action: 'defeat',
      fallbackId: 'hero',
      width: 320,
      height: 819,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'right',
      visualScale: 1,
      opaque: false,
    },

    // Slime Blue Actions (3)
    {
      id: 'slime_blue:attack',
      src: '/battle/monsters/slime_blue_attack.webp',
      kind: 'character',
      action: 'attack',
      fallbackId: 'slime_blue',
      width: 362,
      height: 362,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1,
      opaque: false,
    },
    {
      id: 'slime_blue:hurt',
      src: '/battle/monsters/slime_blue_hurt.webp',
      kind: 'character',
      action: 'hurt',
      fallbackId: 'slime_blue',
      width: 362,
      height: 362,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1,
      opaque: false,
    },
    {
      id: 'slime_blue:defeat',
      src: '/battle/monsters/slime_blue_defeat.webp',
      kind: 'character',
      action: 'defeat',
      fallbackId: 'slime_blue',
      width: 362,
      height: 362,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1,
      opaque: false,
    },

    // Bat Shadow Actions (3)
    {
      id: 'bat_shadow:attack',
      src: '/battle/monsters/bat_shadow_attack.webp',
      kind: 'character',
      action: 'attack',
      fallbackId: 'bat_shadow',
      width: 362,
      height: 362,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1,
      opaque: false,
    },
    {
      id: 'bat_shadow:hurt',
      src: '/battle/monsters/bat_shadow_hurt.webp',
      kind: 'character',
      action: 'hurt',
      fallbackId: 'bat_shadow',
      width: 362,
      height: 362,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1,
      opaque: false,
    },
    {
      id: 'bat_shadow:defeat',
      src: '/battle/monsters/bat_shadow_defeat.webp',
      kind: 'character',
      action: 'defeat',
      fallbackId: 'bat_shadow',
      width: 362,
      height: 362,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1,
      opaque: false,
    },

    // Goblin Green Actions (3)
    {
      id: 'goblin_green:attack',
      src: '/battle/monsters/goblin_green_attack.webp',
      kind: 'character',
      action: 'attack',
      fallbackId: 'goblin_green',
      width: 362,
      height: 362,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1,
      opaque: false,
    },
    {
      id: 'goblin_green:hurt',
      src: '/battle/monsters/goblin_green_hurt.webp',
      kind: 'character',
      action: 'hurt',
      fallbackId: 'goblin_green',
      width: 362,
      height: 362,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1,
      opaque: false,
    },
    {
      id: 'goblin_green:defeat',
      src: '/battle/monsters/goblin_green_defeat.webp',
      kind: 'character',
      action: 'defeat',
      fallbackId: 'goblin_green',
      width: 362,
      height: 362,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1,
      opaque: false,
    },

    // Orc Berserker Actions (3)
    {
      id: 'orc_berserker:attack',
      src: '/battle/monsters/orc_berserker_attack.webp',
      kind: 'character',
      action: 'attack',
      fallbackId: 'orc_berserker',
      width: 362,
      height: 362,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1.25,
      opaque: false,
    },
    {
      id: 'orc_berserker:hurt',
      src: '/battle/monsters/orc_berserker_hurt.webp',
      kind: 'character',
      action: 'hurt',
      fallbackId: 'orc_berserker',
      width: 362,
      height: 362,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1.25,
      opaque: false,
    },
    {
      id: 'orc_berserker:defeat',
      src: '/battle/monsters/orc_berserker_defeat.webp',
      kind: 'character',
      action: 'defeat',
      fallbackId: 'orc_berserker',
      width: 362,
      height: 362,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1.25,
      opaque: false,
    },

    // Skeleton Warrior Actions (3)
    {
      id: 'skeleton_warrior:attack',
      src: '/battle/monsters/skeleton_warrior_attack.webp',
      kind: 'character',
      action: 'attack',
      fallbackId: 'skeleton_warrior',
      width: 362,
      height: 362,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1.25,
      opaque: false,
    },
    {
      id: 'skeleton_warrior:hurt',
      src: '/battle/monsters/skeleton_warrior_hurt.webp',
      kind: 'character',
      action: 'hurt',
      fallbackId: 'skeleton_warrior',
      width: 362,
      height: 362,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1.25,
      opaque: false,
    },
    {
      id: 'skeleton_warrior:defeat',
      src: '/battle/monsters/skeleton_warrior_defeat.webp',
      kind: 'character',
      action: 'defeat',
      fallbackId: 'skeleton_warrior',
      width: 362,
      height: 362,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1.25,
      opaque: false,
    },

    // Skeleton Wizard Actions (3)
    {
      id: 'skeleton_wizard:attack',
      src: '/battle/monsters/skeleton_wizard_attack.webp',
      kind: 'character',
      action: 'attack',
      fallbackId: 'skeleton_wizard',
      width: 362,
      height: 362,
      anchor: { x: 0.5, y: 0.9 },
      facing: 'left',
      visualScale: 1.8,
      opaque: false,
    },
    {
      id: 'skeleton_wizard:hurt',
      src: '/battle/monsters/skeleton_wizard_hurt.webp',
      kind: 'character',
      action: 'hurt',
      fallbackId: 'skeleton_wizard',
      width: 362,
      height: 362,
      anchor: { x: 0.5, y: 0.9 },
      facing: 'left',
      visualScale: 1.8,
      opaque: false,
    },
    {
      id: 'skeleton_wizard:defeat',
      src: '/battle/monsters/skeleton_wizard_defeat.webp',
      kind: 'character',
      action: 'defeat',
      fallbackId: 'skeleton_wizard',
      width: 362,
      height: 362,
      anchor: { x: 0.5, y: 0.9 },
      facing: 'left',
      visualScale: 1.8,
      opaque: false,
    },

    // Dragon Fire Actions (4)
    {
      id: 'dragon_fire:entrance',
      src: '/battle/monsters/dragon_fire_entrance.webp',
      kind: 'character',
      action: 'entrance',
      fallbackId: 'dragon_fire',
      width: 362,
      height: 724,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1.5,
      opaque: false,
    },
    {
      id: 'dragon_fire:attack',
      src: '/battle/monsters/dragon_fire_attack.webp',
      kind: 'character',
      action: 'attack',
      fallbackId: 'dragon_fire',
      width: 362,
      height: 724,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1.5,
      opaque: false,
    },
    {
      id: 'dragon_fire:hurt',
      src: '/battle/monsters/dragon_fire_hurt.webp',
      kind: 'character',
      action: 'hurt',
      fallbackId: 'dragon_fire',
      width: 362,
      height: 724,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1.5,
      opaque: false,
    },
    {
      id: 'dragon_fire:defeat',
      src: '/battle/monsters/dragon_fire_defeat.webp',
      kind: 'character',
      action: 'defeat',
      fallbackId: 'dragon_fire',
      width: 362,
      height: 724,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1.5,
      opaque: false,
    },

    // Backgrounds
    {
      id: 'dungeon-background',
      src: '/battle/dungeon_bg.webp',
      kind: 'background',
      fallbackId: null,
      width: 1024,
      height: 1024,
      opaque: true,
    },
    {
      id: 'dungeon-page-background',
      src: '/battle/dungeon_page_bg.webp',
      kind: 'background',
      fallbackId: 'dungeon-background',
      width: 1024,
      height: 1024,
      opaque: true,
    },

    // 12 Elemental VFX Entries
    {
      id: 'vfx-fire-charge',
      src: '/battle/vfx/fire_charge.webp',
      kind: 'projectile',
      fallbackId: null,
    },
    {
      id: 'vfx-fire-travel',
      src: '/battle/vfx/fire_travel.webp',
      kind: 'projectile',
      fallbackId: null,
    },
    {
      id: 'vfx-fire-impact',
      src: '/battle/vfx/fire_impact.webp',
      kind: 'impact',
      fallbackId: null,
    },
    {
      id: 'vfx-fire-residue',
      src: '/battle/vfx/fire_residue.webp',
      kind: 'impact',
      fallbackId: null,
    },
    {
      id: 'vfx-ice-charge',
      src: '/battle/vfx/ice_charge.webp',
      kind: 'projectile',
      fallbackId: null,
    },
    {
      id: 'vfx-ice-travel',
      src: '/battle/vfx/ice_travel.webp',
      kind: 'projectile',
      fallbackId: null,
    },
    {
      id: 'vfx-ice-impact',
      src: '/battle/vfx/ice_impact.webp',
      kind: 'impact',
      fallbackId: null,
    },
    {
      id: 'vfx-ice-residue',
      src: '/battle/vfx/ice_residue.webp',
      kind: 'impact',
      fallbackId: null,
    },
    {
      id: 'vfx-lightning-charge',
      src: '/battle/vfx/lightning_charge.webp',
      kind: 'projectile',
      fallbackId: null,
    },
    {
      id: 'vfx-lightning-travel',
      src: '/battle/vfx/lightning_travel.webp',
      kind: 'projectile',
      fallbackId: null,
    },
    {
      id: 'vfx-lightning-impact',
      src: '/battle/vfx/lightning_impact.webp',
      kind: 'impact',
      fallbackId: null,
    },
    {
      id: 'vfx-lightning-residue',
      src: '/battle/vfx/lightning_residue.webp',
      kind: 'impact',
      fallbackId: null,
    },

    // 9 Signature Skill Icons
    {
      id: 'skill-fallback',
      src: '/battle/skills/fireball.webp',
      kind: 'skillIcon',
      fallbackId: null,
      width: 418,
      height: 418,
      opaque: false,
    },
    {
      id: 'fireball',
      src: '/battle/skills/fireball.webp',
      kind: 'skillIcon',
      fallbackId: 'skill-fallback',
      width: 418,
      height: 418,
      opaque: false,
    },
    {
      id: 'ice_arrow',
      src: '/battle/skills/ice_arrow.webp',
      kind: 'skillIcon',
      fallbackId: 'skill-fallback',
      width: 418,
      height: 418,
      opaque: false,
    },
    {
      id: 'thunder_bolt',
      src: '/battle/skills/thunder_bolt.webp',
      kind: 'skillIcon',
      fallbackId: 'skill-fallback',
      width: 418,
      height: 418,
      opaque: false,
    },
    {
      id: 'flame_storm',
      src: '/battle/skills/flame_storm.webp',
      kind: 'skillIcon',
      fallbackId: 'skill-fallback',
      width: 418,
      height: 418,
      opaque: false,
    },
    {
      id: 'ice_barrier',
      src: '/battle/skills/ice_barrier.webp',
      kind: 'skillIcon',
      fallbackId: 'skill-fallback',
      width: 418,
      height: 418,
      opaque: false,
    },
    {
      id: 'thunder_hammer',
      src: '/battle/skills/thunder_hammer.webp',
      kind: 'skillIcon',
      fallbackId: 'skill-fallback',
      width: 418,
      height: 418,
      opaque: false,
    },
    {
      id: 'meteor_strike',
      src: '/battle/skills/meteor_strike.webp',
      kind: 'skillIcon',
      fallbackId: 'skill-fallback',
      width: 418,
      height: 418,
      opaque: false,
    },
    {
      id: 'absolute_zero',
      src: '/battle/skills/absolute_zero.webp',
      kind: 'skillIcon',
      fallbackId: 'skill-fallback',
      width: 418,
      height: 418,
      opaque: false,
    },
    {
      id: 'judgment_thunder',
      src: '/battle/skills/judgment_thunder.webp',
      kind: 'skillIcon',
      fallbackId: 'skill-fallback',
      width: 418,
      height: 418,
      opaque: false,
    },

    // Ultimate Videos
    {
      id: 'void_rift',
      src: '/battle/videos/skill_void.webm',
      kind: 'video',
      fallbackId: 'skill-fallback',
    },
    {
      id: 'final_judgment',
      src: '/battle/videos/skill_judgment.webm',
      kind: 'video',
      fallbackId: 'skill-fallback',
    },
    {
      id: 'apocalypse',
      src: '/battle/videos/skill_apocalypse.webm',
      kind: 'video',
      fallbackId: 'skill-fallback',
    },

    // 5 Environment Overlay Entries
    {
      id: 'environment-fog',
      src: '/battle/environment/fog.webp',
      kind: 'environment',
      fallbackId: null,
    },
    {
      id: 'environment-embers',
      src: '/battle/environment/embers.webp',
      kind: 'environment',
      fallbackId: null,
    },
    {
      id: 'environment-shockwave',
      src: '/battle/environment/shockwave.webp',
      kind: 'environment',
      fallbackId: null,
    },
    {
      id: 'environment-speed-lines',
      src: '/battle/environment/speed_lines.webp',
      kind: 'environment',
      fallbackId: null,
    },
    {
      id: 'environment-shadow',
      src: '/battle/environment/shadow.webp',
      kind: 'environment',
      fallbackId: null,
    },

    // BGM and 12 Audio Cue Entries
    {
      id: 'bgm-dungeon',
      src: '/sounds/bgm_dungeon.mp3',
      kind: 'audio',
      fallbackId: null,
    },
    {
      id: 'cue-hit_basic',
      src: '/sounds/battle/hit_basic.ogg',
      kind: 'audio',
      fallbackId: null,
    },
    {
      id: 'cue-hit_critical',
      src: '/sounds/battle/hit_critical.ogg',
      kind: 'audio',
      fallbackId: null,
    },
    {
      id: 'cue-shield_absorb',
      src: '/sounds/battle/shield_absorb.ogg',
      kind: 'audio',
      fallbackId: null,
    },
    {
      id: 'cue-monster_defeat',
      src: '/sounds/battle/monster_defeat.ogg',
      kind: 'audio',
      fallbackId: null,
    },
    {
      id: 'cue-monster_spawn',
      src: '/sounds/battle/monster_spawn.ogg',
      kind: 'audio',
      fallbackId: null,
    },
    {
      id: 'cue-boss_entrance',
      src: '/sounds/battle/boss_entrance.ogg',
      kind: 'audio',
      fallbackId: null,
    },
    {
      id: 'cue-skill_fire_cast',
      src: '/sounds/battle/skill_fire_cast.ogg',
      kind: 'audio',
      fallbackId: null,
    },
    {
      id: 'cue-skill_fire_impact',
      src: '/sounds/battle/skill_fire_impact.ogg',
      kind: 'audio',
      fallbackId: null,
    },
    {
      id: 'cue-skill_ice_cast',
      src: '/sounds/battle/skill_ice_cast.ogg',
      kind: 'audio',
      fallbackId: null,
    },
    {
      id: 'cue-skill_ice_impact',
      src: '/sounds/battle/skill_ice_impact.ogg',
      kind: 'audio',
      fallbackId: null,
    },
    {
      id: 'cue-skill_lightning_cast',
      src: '/sounds/battle/skill_lightning_cast.ogg',
      kind: 'audio',
      fallbackId: null,
    },
    {
      id: 'cue-skill_lightning_impact',
      src: '/sounds/battle/skill_lightning_impact.ogg',
      kind: 'audio',
      fallbackId: null,
    },
  ],
};

export function getBattleAsset(id: string): BattleAssetEntry | null {
  return BATTLE_ASSET_REGISTRY.assets.find(asset => asset.id === id) ?? null;
}

const reportedActionFallbacks = new Set<string>();

export function getBattleCharacterAsset(
  id: string,
  action: NonNullable<BattleAssetEntry['action']>,
): BattleAssetEntry | null {
  const actionAsset = getBattleAsset(`${id}:${action}`);
  if (actionAsset?.kind === 'character') return actionAsset;

  const idleAsset = getBattleAsset(id);
  if (idleAsset?.kind !== 'character') return idleAsset;
  if (action !== 'idle' && import.meta.env.DEV) {
    const diagnosticKey = `${id}:${action}`;
    if (!reportedActionFallbacks.has(diagnosticKey)) {
      reportedActionFallbacks.add(diagnosticKey);
      console.info(`[BattleAssets] ${diagnosticKey} uses the registered idle fallback.`);
    }
  }
  return idleAsset;
}
