import type { BattleAssetEntry, BattleAssetRegistry } from '../types/battleTypes';

/** 唯一 runtime media manifest；概念板與遠端素材不進此表。 */
export const BATTLE_ASSET_REGISTRY: BattleAssetRegistry = {
  assets: [
    {
      id: 'hero',
      src: '/battle/hero.webp',
      kind: 'character',
      action: 'idle',
      fallbackId: null,
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'BattleArena hero sprite',
      width: 500,
      height: 500,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'right',
      visualScale: 1,
      opaque: false,
    },
    {
      id: 'dungeon-background',
      src: '/battle/dungeon_bg.webp',
      kind: 'background',
      fallbackId: null,
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'BattleArena stage background',
      width: 1024,
      height: 1024,
      opaque: true,
    },
    {
      id: 'dungeon-page-background',
      src: '/battle/dungeon_page_bg.webp',
      kind: 'background',
      fallbackId: 'dungeon-background',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'global page background token',
      width: 1024,
      height: 1024,
      opaque: true,
    },
    {
      id: 'slime_blue',
      src: '/battle/monsters/slime_blue.webp',
      kind: 'character',
      action: 'idle',
      fallbackId: 'hero',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'normal monster sprite',
      width: 500,
      height: 500,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1,
      opaque: false,
    },
    {
      id: 'goblin_green',
      src: '/battle/monsters/goblin_green.webp',
      kind: 'character',
      action: 'idle',
      fallbackId: 'hero',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'normal monster sprite',
      width: 500,
      height: 500,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1,
      opaque: false,
    },
    {
      id: 'bat_shadow',
      src: '/battle/monsters/bat_shadow.webp',
      kind: 'character',
      action: 'idle',
      fallbackId: 'hero',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'normal monster sprite',
      width: 500,
      height: 500,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1,
      opaque: false,
    },
    {
      id: 'skeleton_warrior',
      src: '/battle/monsters/skeleton_warrior.webp',
      kind: 'character',
      action: 'idle',
      fallbackId: 'hero',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'elite monster sprite',
      width: 500,
      height: 500,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1.25,
      opaque: false,
    },
    {
      id: 'orc_berserker',
      src: '/battle/monsters/orc_berserker.webp',
      kind: 'character',
      action: 'idle',
      fallbackId: 'hero',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'elite monster sprite',
      width: 500,
      height: 500,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1.25,
      opaque: false,
    },
    {
      id: 'dragon_fire',
      src: '/battle/monsters/dragon_fire.webp',
      kind: 'character',
      action: 'idle',
      fallbackId: 'hero',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'boss monster sprite',
      width: 500,
      height: 500,
      anchor: { x: 0.5, y: 0.85 },
      facing: 'left',
      visualScale: 1.5,
      opaque: false,
    },
    {
      id: 'skeleton_wizard',
      src: '/battle/monsters/skeleton_wizard.webp',
      kind: 'character',
      action: 'idle',
      fallbackId: 'hero',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'boss monster sprite',
      width: 677,
      height: 369,
      anchor: { x: 0.5, y: 0.9 },
      facing: 'left',
      visualScale: 1.8,
      opaque: false,
    },
    {
      id: 'skill-fallback',
      src: '/battle/skills/fireball.webp',
      kind: 'skillIcon',
      action: 'cast',
      fallbackId: null,
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'CSS skill fallback icon',
      width: 500,
      height: 500,
      opaque: false,
    },
    {
      id: 'fireball',
      src: '/battle/skills/fireball.webp',
      kind: 'skillIcon',
      action: 'cast',
      fallbackId: 'skill-fallback',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'basic fire skill icon and projectile',
      width: 500,
      height: 500,
      opaque: false,
    },
    {
      id: 'ice_arrow',
      src: '/battle/skills/ice_arrow.webp',
      kind: 'skillIcon',
      action: 'cast',
      fallbackId: 'skill-fallback',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'basic ice skill icon and projectile',
      width: 500,
      height: 500,
      opaque: false,
    },
    {
      id: 'thunder_bolt',
      src: '/battle/skills/thunder_bolt.webp',
      kind: 'skillIcon',
      action: 'cast',
      fallbackId: 'skill-fallback',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'basic lightning skill icon',
      width: 500,
      height: 500,
      opaque: false,
    },
    {
      id: 'flame_storm',
      src: '/battle/skills/flame_storm.webp',
      kind: 'skillIcon',
      action: 'cast',
      fallbackId: 'skill-fallback',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'intermediate fire skill icon',
      width: 500,
      height: 500,
      opaque: false,
    },
    {
      id: 'ice_barrier',
      src: '/battle/skills/ice_barrier.webp',
      kind: 'skillIcon',
      action: 'cast',
      fallbackId: 'skill-fallback',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'intermediate ice skill icon',
      width: 500,
      height: 500,
      opaque: false,
    },
    {
      id: 'thunder_hammer',
      src: '/battle/skills/thunder_hammer.webp',
      kind: 'skillIcon',
      action: 'cast',
      fallbackId: 'skill-fallback',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'intermediate lightning skill icon',
      width: 500,
      height: 500,
      opaque: false,
    },
    {
      id: 'meteor_strike',
      src: '/battle/skills/meteor_strike.webp',
      kind: 'skillIcon',
      action: 'cast',
      fallbackId: 'skill-fallback',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'advanced fire skill icon',
      width: 500,
      height: 500,
      opaque: false,
    },
    {
      id: 'absolute_zero',
      src: '/battle/skills/absolute_zero.webp',
      kind: 'skillIcon',
      action: 'cast',
      fallbackId: 'skill-fallback',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'advanced ice skill icon',
      width: 1024,
      height: 1024,
      opaque: true,
    },
    {
      id: 'judgment_thunder',
      src: '/battle/skills/judgment_thunder.webp',
      kind: 'skillIcon',
      action: 'cast',
      fallbackId: 'skill-fallback',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'advanced lightning skill icon',
      width: 500,
      height: 500,
      opaque: false,
    },
    {
      id: 'void_rift',
      src: '/battle/videos/skill_void.webm',
      kind: 'video',
      action: 'cast',
      fallbackId: 'skill-fallback',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'ultimate skill video, lazy only',
    },
    {
      id: 'final_judgment',
      src: '/battle/videos/skill_judgment.webm',
      kind: 'video',
      action: 'cast',
      fallbackId: 'skill-fallback',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'epic skill video, lazy only',
    },
    {
      id: 'apocalypse',
      src: '/battle/videos/skill_apocalypse.webm',
      kind: 'video',
      action: 'cast',
      fallbackId: 'skill-fallback',
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'legendary skill video, lazy only',
    },
    {
      id: 'bgm-dungeon',
      src: '/sounds/bgm_dungeon.mp3',
      kind: 'audio',
      action: 'idle',
      fallbackId: null,
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'battle BGM, user setting gated',
    },
    {
      id: 'cue-attack',
      src: '/sounds/attack_fireball.mp3',
      kind: 'audio',
      action: 'attack',
      fallbackId: null,
      status: 'approved',
      sourceNote: 'existing local runtime asset',
      usageNote: 'shared attack cue, event deduped',
    },
  ],
};

export function getBattleAsset(id: string): BattleAssetEntry | null {
  return BATTLE_ASSET_REGISTRY.assets.find(asset => asset.id === id) ?? null;
}

const reportedActionFallbacks = new Set<string>();

export function getBattleCharacterAsset(
  id: string,
  action: NonNullable<BattleAssetEntry['action']>,
): BattleAssetEntry | null {
  const actionAsset = getBattleAsset(`${id}:${action}`);
  if (actionAsset?.kind === 'character') return actionAsset;

  const idleAsset = getBattleAsset(id);
  if (idleAsset?.kind !== 'character') return idleAsset;
  if (action !== 'idle' && import.meta.env.DEV) {
    const diagnosticKey = `${id}:${action}`;
    if (!reportedActionFallbacks.has(diagnosticKey)) {
      reportedActionFallbacks.add(diagnosticKey);
      console.info(`[BattleAssets] ${diagnosticKey} uses the registered idle fallback.`);
    }
  }
  return idleAsset;
}
